/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplicacao;

import telas.RelatorioAnalitico;

/**
 *
 * @author Camilly
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MnuInterno = new javax.swing.JDesktopPane();
        mnuConsProd = new javax.swing.JMenuBar();
        mnuCliente = new javax.swing.JMenu();
        mnuInternoConsCli = new javax.swing.JMenuItem();
        mnuInternoInsCli = new javax.swing.JMenuItem();
        mnuProduto = new javax.swing.JMenu();
        mnuInternoConsProd = new javax.swing.JMenuItem();
        mnuInternoInsProd = new javax.swing.JMenuItem();
        mnuPedido = new javax.swing.JMenu();
        mnuInternoInserirPedido = new javax.swing.JMenuItem();
        mnuInternoConsultarPedido = new javax.swing.JMenuItem();
        mnuRelatorios = new javax.swing.JMenu();
        mnuInternoReAnalitico = new javax.swing.JMenuItem();
        mnuInternoReSintetico = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SPEED SHOES");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout MnuInternoLayout = new javax.swing.GroupLayout(MnuInterno);
        MnuInterno.setLayout(MnuInternoLayout);
        MnuInternoLayout.setHorizontalGroup(
            MnuInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        MnuInternoLayout.setVerticalGroup(
            MnuInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        mnuCliente.setText("Cliente");

        mnuInternoConsCli.setText("Consultar");
        mnuInternoConsCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInternoConsCliActionPerformed(evt);
            }
        });
        mnuCliente.add(mnuInternoConsCli);

        mnuInternoInsCli.setText("Inserir");
        mnuInternoInsCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInternoInsCliActionPerformed(evt);
            }
        });
        mnuCliente.add(mnuInternoInsCli);

        mnuConsProd.add(mnuCliente);

        mnuProduto.setText("Produto");

        mnuInternoConsProd.setText("Consultar");
        mnuInternoConsProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInternoConsProdActionPerformed(evt);
            }
        });
        mnuProduto.add(mnuInternoConsProd);

        mnuInternoInsProd.setText("Inserir");
        mnuInternoInsProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInternoInsProdActionPerformed(evt);
            }
        });
        mnuProduto.add(mnuInternoInsProd);

        mnuConsProd.add(mnuProduto);

        mnuPedido.setText("Pedido");

        mnuInternoInserirPedido.setText("Inserir");
        mnuInternoInserirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInternoInserirPedidoActionPerformed(evt);
            }
        });
        mnuPedido.add(mnuInternoInserirPedido);

        mnuInternoConsultarPedido.setText("Consultar");
        mnuInternoConsultarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInternoConsultarPedidoActionPerformed(evt);
            }
        });
        mnuPedido.add(mnuInternoConsultarPedido);

        mnuConsProd.add(mnuPedido);

        mnuRelatorios.setText("Relatórios");

        mnuInternoReAnalitico.setText("Analítico");
        mnuInternoReAnalitico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInternoReAnaliticoActionPerformed(evt);
            }
        });
        mnuRelatorios.add(mnuInternoReAnalitico);

        mnuInternoReSintetico.setText("Sintético");
        mnuInternoReSintetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInternoReSinteticoActionPerformed(evt);
            }
        });
        mnuRelatorios.add(mnuInternoReSintetico);

        mnuConsProd.add(mnuRelatorios);

        setJMenuBar(mnuConsProd);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MnuInterno)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MnuInterno)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuInternoConsCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInternoConsCliActionPerformed
        MnuInternoConsCliente tela = new MnuInternoConsCliente();
        tela.setVisible(true);
        
        this.MnuInterno.add(tela);
    }//GEN-LAST:event_mnuInternoConsCliActionPerformed

    private void mnuInternoInsCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInternoInsCliActionPerformed
        MnuInternoInsCliente tela = new MnuInternoInsCliente();
        tela.setVisible(true);
        
        this.MnuInterno.add(tela);
    }//GEN-LAST:event_mnuInternoInsCliActionPerformed

    private void mnuInternoConsProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInternoConsProdActionPerformed
        MnuInternoConsProduto tela = new MnuInternoConsProduto();
        tela.setVisible(true);
        
        this.MnuInterno.add(tela);
    }//GEN-LAST:event_mnuInternoConsProdActionPerformed

    private void mnuInternoInsProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInternoInsProdActionPerformed
        MnuInternoInsProduto tela = new MnuInternoInsProduto();
        tela.setVisible(true);
        
        this.MnuInterno.add(tela);
    }//GEN-LAST:event_mnuInternoInsProdActionPerformed

    private void mnuInternoConsultarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInternoConsultarPedidoActionPerformed
        MnuInternoConsultarPedido tela = new MnuInternoConsultarPedido();
        tela.setVisible(true);

        this.MnuInterno.add(tela);
    }//GEN-LAST:event_mnuInternoConsultarPedidoActionPerformed

    private void mnuInternoInserirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInternoInserirPedidoActionPerformed
        MnuInternoInserirPedido tela = new MnuInternoInserirPedido();
        tela.setVisible(true);

        this.MnuInterno.add(tela);    // TODO add your handling code here:
    }//GEN-LAST:event_mnuInternoInserirPedidoActionPerformed

    private void mnuInternoReSinteticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInternoReSinteticoActionPerformed
        MnuInternoRelatorioSintetico tela = new MnuInternoRelatorioSintetico();
        tela.setVisible(true);
        
        this.MnuInterno.add(tela);
    }//GEN-LAST:event_mnuInternoReSinteticoActionPerformed

    private void mnuInternoReAnaliticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInternoReAnaliticoActionPerformed
        MnuInternoRelatorioAnalitico tela = new MnuInternoRelatorioAnalitico();
        tela.setVisible(true);
        
        this.MnuInterno.add(tela);
    }//GEN-LAST:event_mnuInternoReAnaliticoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane MnuInterno;
    private javax.swing.JMenu mnuCliente;
    private javax.swing.JMenuBar mnuConsProd;
    private javax.swing.JMenuItem mnuInternoConsCli;
    private javax.swing.JMenuItem mnuInternoConsProd;
    private javax.swing.JMenuItem mnuInternoConsultarPedido;
    private javax.swing.JMenuItem mnuInternoInsCli;
    private javax.swing.JMenuItem mnuInternoInsProd;
    private javax.swing.JMenuItem mnuInternoInserirPedido;
    private javax.swing.JMenuItem mnuInternoReAnalitico;
    private javax.swing.JMenuItem mnuInternoReSintetico;
    private javax.swing.JMenu mnuPedido;
    private javax.swing.JMenu mnuProduto;
    private javax.swing.JMenu mnuRelatorios;
    // End of variables declaration//GEN-END:variables
}
